server:
  port: 8080

mybatis:
  mapper-locations: classpath*:/com/example/apidemo/mapper/*.xml
  type-aliases-package: com.example.apidemo.entity
  executor-type: simple
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  params: count=countSql

# 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/api-demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
